export default {
  // Sidebar / nav
  back_to_catalog: '← Back to courses',
  toggle_theme: 'Toggle theme',
  toggle_lang: 'Switch language',
  open_menu: 'Open menu',
  close_menu: 'Close menu',
  prev: 'Previous',
  next: 'Next',
  mark_finished: '✓ Mark chapter as finished',
  mark_finished_undo: '✓ Finished — click to undo',

  // Block labels
  analogy: 'Analogy',
  prerequisites: 'Prerequisites',
  takeaways: 'Key takeaways',
  resources: 'Resources',
  diagram: 'Diagram',
  example: 'Worked example',
  quote: 'Quote',

  // Quiz
  quiz: 'Quick check',
  quiz_submit: 'Submit answers',
  quiz_retry: 'Try again',
  quiz_correct: '✓ Correct',
  quiz_incorrect: '✗ Not quite',
  quiz_select_all: 'Answer every question to submit.',
  quiz_score: 'You scored {score} out of {total}.',
  quiz_pass: '🎉 Great job — you nailed it.',
  quiz_fail: 'Take another look at the chapter and retry.',

  // Closing chapter
  course_complete: '🎉 Course complete!',
  final_recap: 'Final recap',
  advanced_topics: 'Advanced topics not covered',
  next_projects: 'Suggested next projects',
  external_resources: 'Curated external resources',
  roadmap: 'Learning roadmap',
  reinforces: 'Reinforces',
  difficulty_easy: '🟢 Easy',
  difficulty_intermediate: '🟡 Intermediate',
  difficulty_challenging: '🔴 Challenging',

  // Translation status
  original_lang_notice: 'This course is not yet translated — showing the original version.',

  // Catalog (homepage)
  cat_title: 'Crash Courses — The 20% That Delivers 80%',
  cat_logo: '◆ My Courses',
  cat_hero_badge: '{count} interactive courses · built on the 80/20 Pareto Principle',
  cat_hero_badge_one: '{count} interactive course · built on the 80/20 Pareto Principle',
  cat_hero_h1_1: 'Learn the ',
  cat_hero_h1_gradient: '20% that delivers 80%',
  cat_hero_h1_2: ' of the value',
  cat_hero_lede: 'Premium, single-file interactive crash courses on any subject — ruthlessly focused on the vital few concepts that actually matter. Skip the fluff, build real intuition fast.',
  cat_stat_courses: 'Courses',
  cat_stat_pareto: 'Pareto-driven',
  cat_stat_deps: 'Dependencies',
  cat_pareto_h2_1: 'The ',
  cat_pareto_h2_accent: 'Pareto Principle',
  cat_pareto_h2_2: ' shapes every course',
  cat_pareto_lede: 'In 1896, economist Vilfredo Pareto noticed that ~80% of effects come from ~20% of causes. We apply that same lens to learning: identify the small set of ideas that unlock most of the practical value of a subject — and build the course around them. Trivial details get demoted to the closing chapter, not the critical path.',
  cat_pillar_vital: 'Vital few, not trivial many',
  cat_pillar_fluency: 'Faster time to fluency',
  cat_pillar_concrete: 'Concrete examples over theory',
  cat_pillar_path: 'Clear path to "what\'s next"',
  cat_search_placeholder: 'Search courses, technologies, topics...',
  cat_filter_all: 'All topics',
  cat_filter_backend: 'Backend',
  cat_filter_frontend: 'Frontend',
  cat_filter_mobile: 'Mobile',
  cat_filter_architecture: 'Architecture',
  cat_filter_devops: 'DevOps',
  cat_filter_cloud: 'Cloud',
  cat_filter_fundamentals: 'Fundamentals',
  cat_sidebar_title: 'Subjects',
  cat_sidebar_close: 'Close subjects',
  cat_sidebar_hint: 'Press',
  cat_sidebar_hint_close: 'to close',
  cat_subject_all: 'All',
  cat_subject_dev_short: 'Development',
  cat_subject_cloud_short: 'Cloud & DevOps',
  cat_empty_h3: 'No courses found',
  cat_empty_lede: 'Try adjusting your search or filters.',
  cat_footer: 'Crafted with care · Single-file interactive courses · 80/20 Pareto-driven · ',
  cat_footer_link: 'View on GitHub',

  // Course meta labels
  level_beginner: 'Beginner',
  level_intermediate: 'Intermediate',
  level_advanced: 'Advanced',
  meta_hours: '~{n} hours',
  meta_chapters: '{n} chapters',
  cta_start: 'Start course',
};
