export default {
  // Sidebar / nav
  back_to_catalog: '← Retour aux cours',
  toggle_theme: 'Changer de thème',
  toggle_lang: 'Changer de langue',
  open_menu: 'Ouvrir le menu',
  close_menu: 'Fermer le menu',
  prev: 'Précédent',
  next: 'Suivant',
  mark_finished: '✓ Marquer ce chapitre comme terminé',
  mark_finished_undo: '✓ Terminé — cliquer pour annuler',

  analogy: 'Analogie',
  prerequisites: 'Pré-requis',
  takeaways: 'À retenir',
  resources: 'Ressources',
  diagram: 'Schéma',
  example: 'Exemple',
  quote: 'Citation',

  quiz: 'Mini quiz',
  quiz_submit: 'Valider mes réponses',
  quiz_retry: 'Réessayer',
  quiz_correct: '✓ Bonne réponse',
  quiz_incorrect: '✗ Pas tout à fait',
  quiz_select_all: 'Réponds à toutes les questions avant de valider.',
  quiz_score: 'Tu as {score} sur {total}.',
  quiz_pass: '🎉 Bravo — tu maîtrises ce chapitre.',
  quiz_fail: 'Relis le chapitre et réessaie.',

  course_complete: '🎉 Cours terminé !',
  final_recap: 'Récapitulatif final',
  advanced_topics: 'Sujets avancés non couverts',
  next_projects: 'Projets suggérés pour aller plus loin',
  external_resources: 'Ressources externes recommandées',
  roadmap: 'Feuille de route',
  reinforces: 'Renforce',
  difficulty_easy: '🟢 Facile',
  difficulty_intermediate: '🟡 Intermédiaire',
  difficulty_challenging: '🔴 Challengeant',

  original_lang_notice: 'Ce cours n\'est pas encore traduit — version originale affichée.',

  // Catalog (page d'accueil)
  cat_title: 'Crash Courses — Les 20% qui produisent 80% du résultat',
  cat_logo: '◆ Mes Cours',
  cat_hero_badge: '{count} cours interactifs · basés sur le principe de Pareto 80/20',
  cat_hero_badge_one: '{count} cours interactif · basé sur le principe de Pareto 80/20',
  cat_hero_h1_1: 'Apprends les ',
  cat_hero_h1_gradient: '20% qui produisent 80%',
  cat_hero_h1_2: ' du résultat',
  cat_hero_lede: 'Des crash courses interactifs et premium sur n\'importe quel sujet — concentrés sans pitié sur le petit nombre de concepts qui comptent vraiment. Saute le superflu, construis une vraie intuition vite.',
  cat_stat_courses: 'Cours',
  cat_stat_pareto: 'Loi de Pareto',
  cat_stat_deps: 'Dépendances',
  cat_pareto_h2_1: 'Le ',
  cat_pareto_h2_accent: 'principe de Pareto',
  cat_pareto_h2_2: ' façonne chaque cours',
  cat_pareto_lede: 'En 1896, l\'économiste Vilfredo Pareto a remarqué qu\'environ 80% des effets viennent d\'environ 20% des causes. On applique la même grille de lecture à l\'apprentissage : identifier le petit ensemble d\'idées qui débloque l\'essentiel de la valeur pratique d\'un sujet — et construire le cours autour. Les détails triviaux sont relégués au chapitre final, pas dans le chemin critique.',
  cat_pillar_vital: 'L\'essentiel, pas l\'accessoire',
  cat_pillar_fluency: 'Devenir fluide plus vite',
  cat_pillar_concrete: 'Exemples concrets, pas de théorie pure',
  cat_pillar_path: 'Une suite claire pour aller plus loin',
  cat_search_placeholder: 'Rechercher cours, technos, sujets...',
  cat_filter_all: 'Tous les sujets',
  cat_filter_backend: 'Backend',
  cat_filter_frontend: 'Frontend',
  cat_filter_mobile: 'Mobile',
  cat_filter_architecture: 'Architecture',
  cat_filter_devops: 'DevOps',
  cat_filter_cloud: 'Cloud',
  cat_filter_fundamentals: 'Fondamentaux',
  cat_sidebar_title: 'Sujets',
  cat_sidebar_close: 'Fermer les sujets',
  cat_sidebar_hint: 'Appuie sur',
  cat_sidebar_hint_close: 'pour fermer',
  cat_subject_all: 'Tous',
  cat_subject_dev_short: 'Développement',
  cat_subject_cloud_short: 'Cloud & DevOps',
  cat_empty_h3: 'Aucun cours trouvé',
  cat_empty_lede: 'Ajuste ta recherche ou tes filtres.',
  cat_footer: 'Conçu avec soin · Cours interactifs en un fichier · Pareto 80/20 · ',
  cat_footer_link: 'Voir sur GitHub',

  // Métadonnées de cours
  level_beginner: 'Débutant',
  level_intermediate: 'Intermédiaire',
  level_advanced: 'Avancé',
  meta_hours: '~{n} heures',
  meta_chapters: '{n} chapitres',
  cta_start: 'Commencer',
};
